# Generated by Django 4.0.2 on 2022-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('reseller_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('date_of_joining', models.DateTimeField(default='2022-02-14 15:13:20')),
            ],
        ),
        migrations.CreateModel(
            name='Wholseller',
            fields=[
                ('wholeseller_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('date_of_joining', models.DateTimeField(default='2022-02-14 15:13:20')),
            ],
        ),
    ]
